# Generated by Django 5.1.4 on 2025-01-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_rating_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
